=== datacite/schema/source/archive/kernel-2.2/metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Revision history
     2010-08-26   Complete revision according to new common specification by the metadata work group after review. AJH, DTIC
	 2010-11-17 Revised to current state of kernel review, FZ, TIB 
	 2011-01-17 Complete revision after community review. FZ, TIB
	 2011-03-17 Release of v2.1: added a namespace; mandatory properties got minLength; changes in the definitions of relationTypes
	 IsDocumentedBy/Documents and isCompiledBy/Compiles; changes type of property "Date" from xs:date to xs:string. FZ, TIB
	 2011-06-27 v2.2: namespace: kernel-2.2, additions to controlled lists "resourceType", "contributorType", "relatedIdentifierType", and "descriptionType". Removal of intermediate include-files.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://datacite.org/schema/kernel-2.2" targetNamespace="http://datacite.org/schema/kernel-2.2" elementFormDefault="qualified" xml:lang="EN">
	<xs:include schemaLocation="include/datacite-titleType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-contributorType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-dateType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-resourceType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-relationType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-relatedIdentifierType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-descriptionType-v2.xsd"/>
	<xs:element name="resource">
		<xs:annotation>
			<xs:documentation>
	Root element of a single record. This wrapper element is for XML implementation only and is not defined in the DataCite DOI standard.
        Note: This is the case for any wrapper element within this schema!</xs:documentation>
			<xs:documentation>No content in this wrapper element.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<!--REQUIRED FIELDS-->
				<xs:element name="identifier">
					<xs:annotation>
						<xs:documentation>A persistent identifier that identifies a resource.</xs:documentation>
						<xs:documentation>Currently, only DOI is allowed.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="doiType">
								<xs:attribute name="identifierType" use="required" fixed="DOI"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="creators">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="creator" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The main researchers involved working on the data, or the authors of the publication in priority order. May be a corporate/institutional or personal name.</xs:documentation>
									<xs:documentation>Format: Family, Given.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="creatorName">
											<xs:simpleType>
												<xs:restriction base="nonemptycontentStringType"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="nameIdentifier" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="nonemptycontentStringType">
														<xs:attribute name="nameIdentifierScheme" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="titles">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>A name or title by which a resource is known.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="nonemptycontentStringType">
											<xs:attribute name="titleType" type="titleType" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="publisher">
					<xs:annotation>
						<xs:documentation>A holder of the data (including archives as appropriate) or institution which submitted the work. Any others may be listed as contributors. This property will be used to formulate the citation, so consider the prominence of the role.</xs:documentation>
						<xs:documentation>Examples: World Data Center for Climate (WDCC); GeoForschungsZentrum Potsdam (GFZ); Geological Institute, University of Tokyo </xs:documentation>
						<xs:documentation>In the case of datasets, "publish" is understood to mean making the data available to the community of researchers.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="nonemptycontentStringType"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="publicationYear">
					<xs:annotation>
						<xs:documentation>Year when the data is made publicly available. If an embargo period has been in effect, use the date when the embargo period ends.</xs:documentation>
						<xs:documentation>YYYY</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="yearType"/>
					</xs:simpleType>
				</xs:element>
				<!--OPTIONAL FIELDS-->
				<xs:element name="subjects" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="subject" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Subject, keywords, classification codes, or key phrases describing the resource.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="subjectScheme" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="contributors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="contributor" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The institution or person responsible for collecting, creating, or otherwise contributing to the development of the dataset.</xs:documentation>
									<xs:documentation>The personal name format should be: Family, Given.</xs:documentation>
								</xs:annotation>
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element name="contributorName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="nameIdentifier" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="nameIdentifierScheme" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="contributorType" type="contributorType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dates" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="date" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Different dates relevant to the work.</xs:documentation>
									<xs:documentation>YYYY or YYYY-MM-DD or any other format described in W3CDTF (http://www.w3.org/TR/NOTE-datetime) </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="dateType" type="dateType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="language" type="xs:language" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Primary language of the resource. Allowed values from: ISO 639-2/B, ISO 639-3</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="resourceType" minOccurs="0">
					<xs:annotation>
						<xs:documentation>The type of a resource. You may enter an additional free text description.</xs:documentation>
					</xs:annotation>
					<xs:complexType mixed="true">
						<xs:annotation>
							<xs:documentation>Use this attribute to choose the general type of the resource from the controlled list.</xs:documentation>
						</xs:annotation>
						<xs:attribute name="resourceTypeGeneral" type="resourceType" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="alternateIdentifiers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alternateIdentifier" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>An identifier other than the primary identifier applied to the resource being registered. This may be any alphanumeric string which is unique within its domain of issue. The format is open</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="alternateIdentifierType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="relatedIdentifiers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="relatedIdentifier" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Identifiers of related resources. Use this property to indicate subsets of properties, as appropriate.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="relatedIdentifierType" type="relatedIdentifierType" use="required"/>
											<xs:attribute name="relationType" type="relationType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sizes" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="size" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Unstructures size information about the resource. </xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="formats" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="format" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Technical format of the resource.</xs:documentation>
									<xs:documentation>Use file extension or MIME type where possible.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="version" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Version number of the resource. If the primary resource has changed the version number increases.</xs:documentation>
						<xs:documentation>Register a new DOI (or primary identifier) when the version of the resource changes to enable the citation of the exact version of a research dataset (or other resource). May be used in conjunction with properties 11 and 12 (AlternateIdentifier and RelatedIdentifier) to indicate various information updates.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="rights" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Any rights information for this resource. Provide a rights management statement for the resource or reference a service providing such information. Include embargo information if applicable.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="descriptions" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="description" maxOccurs="unbounded">
								<xs:complexType mixed="true">
									<xs:choice>
										<xs:element name="br" minOccurs="0" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="0"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:choice>
									<xs:attribute name="descriptionType" type="descriptionType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="lastMetadataUpdate" type="xs:date" use="optional"/>
			<xs:attribute name="metadataVersionNumber" type="xs:integer" use="optional"/>
			<!--ADMINISTRATIVE FIELDS-->
		</xs:complexType>
	</xs:element>
	<!-- TYPE DECLARATIONS -->
	<!-- defines the value for a DOI: DOI must start with "10."  -->
	<xs:simpleType name="doiType">
		<xs:restriction base="xs:token">
			<xs:pattern value="[1][0][/.].*"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- defines value for mandatory fields -->
	<xs:simpleType name="nonemptycontentStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="nameId">
		<xs:attribute name="nameIdentifier" type="xs:string" use="optional"/>
		<xs:attribute name="nameIdentifierScheme" type="xs:string" use="optional"/>
	</xs:attributeGroup>
	<!-- defines the value for a year -->
	<xs:simpleType name="yearType">
		<xs:restriction base="xs:token">
			<xs:pattern value="[\d]{4}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== datacite/schema/source/meta/kernel-4.7/example/datacite-example-relationtypeinformation-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://datacite.org/schema/kernel-4"
    xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4/metadata.xsd">
    <identifier identifierType="DOI">10.82433/0320-9g16</identifier>
    <creators>
        <creator>
            <creatorName nameType="Personal">Garcia, Sofia</creatorName>
            <givenName>Sofia</givenName>
            <familyName>Garcia</familyName>
            <nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID">
                https://orcid.org/0000-0001-5727-2427</nameIdentifier>
            <affiliation affiliationIdentifier="https://ror.org/03efmqc40"
                affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Arizona State
                University</affiliation>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en">Comment on "Improving Metadata Quality in Scholarly Repositories"</title>
    </titles>
    <publisher>Global Open Research</publisher>
    <publicationYear>2025</publicationYear>
    <resourceType resourceTypeGeneral="Preprint" />
    <relatedIdentifiers>
        <relatedIdentifier relatedIdentifierType="DOI" relationType="Other"
            relationTypeInformation="is reply to" resourceTypeGeneral="JournalArticle">10.82433/e34e-y143</relatedIdentifier>
    </relatedIdentifiers>
    <language>en</language>
    <descriptions>
        <description xml:lang="en" descriptionType="Abstract">This preprint provides a response to
            the article "Improving Metadata Quality in Scholarly Repositories." It discusses
            additional considerations for enhancing metadata completeness, consistency, and
            interoperability. The authors highlight practical workflows, offer examples of common
            metadata challenges, and suggest strategies to improve discoverability and reuse of
            repository content.</description>
    </descriptions>
</resource>

=== datacite/schema/source/meta/kernel-4.7/example/datacite-example-presentation-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://datacite.org/schema/kernel-4"
    xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4/metadata.xsd">
    <identifier identifierType="DOI">10.82433/v14f-gk24</identifier>
    <creators>
        <creator>
            <creatorName nameType="Personal">Garcia, Sofia</creatorName>
            <givenName>Sofia</givenName>
            <familyName>Garcia</familyName>
            <nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID">
                https://orcid.org/0000-0001-5727-2427</nameIdentifier>
            <affiliation affiliationIdentifier="https://ror.org/03efmqc40"
                affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Arizona State
                University</affiliation>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en">DOIs in Action: Making Presentations More Discoverable</title>
    </titles>
    <publisher>International Metadata Forum</publisher>
    <publicationYear>2025</publicationYear>
    <dates>
        <date dateType="Issued">2025-08-11</date>
    </dates>
    <resourceType resourceTypeGeneral="Presentation">Conference presentation</resourceType>
    <relatedIdentifiers>
        <relatedIdentifier relatedIdentifierType="URL" relationType="Other"
            relationTypeInformation="was presented at" resourceTypeGeneral="Event">https://example.org/metadata-forum-2025</relatedIdentifier>
        <relatedIdentifier relatedIdentifierType="DOI" relationType="IsVariantFormOf"
            resourceTypeGeneral="Audiovisual">10.82433/9jbk-4c28</relatedIdentifier>
    </relatedIdentifiers>
    <language>en</language>
    <rightsList>
        <rights xml:lang="en" schemeURI="https://spdx.org/licenses/" rightsIdentifierScheme="SPDX"
            rightsIdentifier="CC-BY-4.0" rightsURI="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International</rights>
    </rightsList>
    <descriptions>
        <description xml:lang="en" descriptionType="Abstract">Conference presentations are often
            overlooked in discovery and citation systems. This presentation demonstrates practical
            workflows for assigning DOIs to presentations, linking them to related datasets and
            publications, and embedding identifiers in slide decks for easy sharing. By applying
            these strategies, researchers can increase the visibility, impact, and reusability of
            their talks beyond the event itself.</description>
    </descriptions>
</resource>

=== datacite/schema/source/meta/kernel-4.3/example/datacite-example-GeoLocation-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.3/metadata.xsd">
  <identifier identifierType="DOI">10.5072/geoPointExample</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Schumann, Kai</creatorName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Völker, David</creatorName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Weinrebe, Wilhelm Reiber</creatorName>
    </creator>
  </creators>
  <titles>
    <title xml:lang="en">
      Gridded results of swath bathymetric mapping of Disko Bay, Western Greenland, 2007-2008
    </title>
  </titles>
  <publisher xml:lang="en">
    PANGAEA - Data Publisher for Earth &amp; Environmental Science
  </publisher>
  <publicationYear>2011</publicationYear>
  <subjects>
    <subject xml:lang="en" subjectScheme="DDC">551 Geology, hydrology, meteorology</subject>
  </subjects>
  <contributors>
    <contributor contributorType="HostingInstitution">
      <contributorName nameType="Organizational">
        IFM-GEOMAR Leibniz-Institute of Marine Sciences, Kiel University
      </contributorName>
      <nameIdentifier nameIdentifierScheme="ROR" schemeURI="http://ror.org/">https://ror.org/02h2x0161</nameIdentifier>
    </contributor>
  </contributors>
  <language>en</language>
  <resourceType resourceTypeGeneral="Dataset"/>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="Continues">10.5072/timeSeries</relatedIdentifier>
  </relatedIdentifiers>
  <sizes>
    <size>4 datasets</size>
  </sizes>
  <formats>
    <format>application/zip</format>
  </formats>
  <rightsList>
    <rights xml:lang="en-US" schemeURI="https://spdx.org/licenses/" rightsIdentifierScheme="SPDX" rightsIdentifier="
CC-BY-3.0"  rightsURI="http://creativecommons.org/licenses/by/3.0/deed">Creative Commons Attribution-NoDerivs 2.0 Generic</rights></rightsList>
  <descriptions>
    <description xml:lang="en" descriptionType="Abstract">
      A ship-based acoustic mapping campaign was conducted at the exit of Ilulissat Ice Fjord and in the sedimentary basin of Disko Bay to the west of the fjord mouth. Submarine landscape and sediment distribution patterns are interpreted in terms of
      glaciomarine facies types that are related to variations in the past position of the glacier front. In particular, asymmetric ridges that form a curved entity and a large sill at the fjord mouth may represent moraines hat depict at least two
      relatively stable positions of the ice front in the Disko Bay and at the fjord mouth. In this respect, Ilulissat Glacier shows prominent differences to the East Greenland Kangerlussuaq Glacier which is comparable in present size and present role for
      the ice discharge from the inland ice sheet. Two linear clusters of pockmarks in the center of the sedimentary basin seem to be linked to ongoing methane release due to dissociation of gas hydrates, a process fueled by climate warming in the Arctic
      realm.
    </description>
  </descriptions>
  <geoLocations>
    <geoLocation>
      <geoLocationPlace>Disko Bay</geoLocationPlace>
      <geoLocationPoint>
        <pointLongitude>-52.000000</pointLongitude>
        <pointLatitude>69.000000</pointLatitude>
      </geoLocationPoint>
    </geoLocation>
  </geoLocations>
</resource>

=== datacite/schema/source/meta/kernel-4.4/example/datacite-example-HasMetadata-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.2/metadata.xsd">
  <identifier identifierType="DOI">10.5072/example</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Mari, Bernard</creatorName>
      <givenName>Bernard</givenName>
      <familyName>Mari</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Puissegur, Marie-Pierre</creatorName>
      <givenName>Marie-Pierre</givenName>
      <familyName>Puissegur</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Barbry, Pascal</creatorName>
      <givenName>Pascal</givenName>
      <familyName>Barbry</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Lebrigand, Kevin</creatorName>
      <givenName>Kevin</givenName>
      <familyName>Lebrigand</familyName>
    </creator>
  </creators>
  <titles>
    <title xml:lang="en">
      Identification of putative novel specific targets of mir-210 in A549 human adenocarcinoma cells
    </title>
  </titles>
  <publisher xml:lang="fr">
    Institut de Pharmacologie Moleculaire et Cellulaire (IPMC), CNRS UMR6097, Universite de Nice Sophia-Antipolis, 660 route des lucioles, 06560 Valbonne - Sophia-Antipolis, France
  </publisher>
  <publicationYear>2010</publicationYear>
  <subjects>
    <subject schemeURI="http://www.nlm.nih.gov/mesh/meshhome.html" subjectScheme="Mesh">Neoplasms</subject>
    <subject schemeURI="http://purl.obolibrary.org/obo/obi" subjectScheme="OBI">Transcription profiling</subject>
    <subject schemeURI="http://www.ncbi.nlm.nih.gov/Taxonomy/" subjectScheme="NCBITaxon">Homo sapiens</subject>
    <subject schemeURI="http://www.ebi.ac.uk/efo" subjectScheme="Mesh">A549</subject>
    <subject schemeURI="http://purl.obolibrary.org/obo/obi" subjectScheme="OBI">DNA microarray</subject>
  </subjects>
  <contributors>
    <contributor contributorType="HostingInstitution">
      <contributorName xml:lang="fr" nameType="Organizational">INIST-CNRS</contributorName>
    </contributor>
  </contributors>
  <language>en</language>
  <resourceType resourceTypeGeneral="Text">Experiment report</resourceType>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="URL" relatedMetadataScheme="ISA-Tab" relationType="HasMetadata" schemeType="Text" schemeURI="http://isatab.sourceforge.net/docs/ISA-TAB_release-candidate-1_v1.0_24nov08.pdf">http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE18695</relatedIdentifier>
  </relatedIdentifiers>
  <sizes>
    <size>183 ko</size>
    <size>3 pages</size>
  </sizes>
  <formats>
    <format>PDF</format>
  </formats>
  <rightsList>
    <rights xml:lang="en-US" schemeURI="https://spdx.org/licenses/"   rightsIdentifierScheme="SPDX" rightsIdentifier="CC-BY-NC-ND-3.0"  rightsURI="http://creativecommons.org/licenses/by-nc-nd/3.0/"/>  </rightsList>
  <descriptions>
    <description xml:lang="en" descriptionType="Abstract">
      To identify putative novel specific targets of mir-210, we overexpressed miR-210 as well as miR-34a and a siRNA targeted against E2F3 in A549 human adenocarcinoma cells by transfecting them with synthetic pre-miRNAs or a synthetic negative pre-miRNA
      as control (miR-Neg). RNA samples were harvested at 48 hours post-transfection and 2 independent experiments performed in dye-swap: miR-210 versus miR-Neg ; miR-34a versus miR-Neg ; si-E2F3 versus miR-Neg ; si-control versus miR-Neg.
    </description>
  </descriptions>
</resource>

=== datacite/schema/source/meta/kernel-2.2/example/datacite-metadata-sample-complicated-v2.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-2.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-2.2 http://schema.datacite.org/meta/kernel-2.2/metadata.xsd">
	<identifier identifierType="DOI">10.5072/testpub</identifier>
	<creators>
		<creator>
			<creatorName>Smith, John</creatorName>
		</creator>
		<creator>
			<creatorName>つまらないものですが</creatorName>
			<nameIdentifier nameIdentifierScheme="ISNI">abc123</nameIdentifier>
		</creator>
	</creators>
	<titles>
		<title>Właściwości rzutowań podprzestrzeniowych</title>
		<title titleType="TranslatedTitle">Translation of Polish titles</title>
	</titles>
	<publisher>Springer</publisher>
	<publicationYear>2010</publicationYear>
	<subjects>
		<subject subjectScheme="DDC">830 German &amp; related literatures</subject>
		<subject>Polish Literature</subject>
	</subjects>
	<contributors>
		<contributor contributorType="DataCollector">
			<contributorName>Doe, John</contributorName>
			<nameIdentifier nameIdentifierScheme="ORCID">456xyz</nameIdentifier>
		</contributor>
	</contributors>
	<dates>
		<date dateType="StartDate">2009-04-29</date>
		<date dateType="EndDate">2010-01-05</date>
	</dates>
	<language>GER</language>
	<resourceType resourceTypeGeneral="Text">Monograph</resourceType>
	<alternateIdentifiers>
		<alternateIdentifier alternateIdentifierType="ISBN">937-0-4523-12357-6</alternateIdentifier>
	</alternateIdentifiers>
	<relatedIdentifiers>
		<relatedIdentifier relatedIdentifierType="DOI" relationType="IsPartOf">10.5272/oldertestpub</relatedIdentifier>
	</relatedIdentifiers>
	<sizes>
		<size>256 pages</size>
	</sizes>
	<formats>
		<format>pdf</format>
	</formats>
	<version>2</version>
	<rights>CC by-nd</rights>
	<descriptions>
		<description descriptionType="Abstract">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</description>
	</descriptions>
</resource>
