=== datacite/schema/source/archive/kernel-2.2/metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Revision history
     2010-08-26   Complete revision according to new common specification by the metadata work group after review. AJH, DTIC
	 2010-11-17 Revised to current state of kernel review, FZ, TIB 
	 2011-01-17 Complete revision after community review. FZ, TIB
	 2011-03-17 Release of v2.1: added a namespace; mandatory properties got minLength; changes in the definitions of relationTypes
	 IsDocumentedBy/Documents and isCompiledBy/Compiles; changes type of property "Date" from xs:date to xs:string. FZ, TIB
	 2011-06-27 v2.2: namespace: kernel-2.2, additions to controlled lists "resourceType", "contributorType", "relatedIdentifierType", and "descriptionType". Removal of intermediate include-files.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://datacite.org/schema/kernel-2.2" targetNamespace="http://datacite.org/schema/kernel-2.2" elementFormDefault="qualified" xml:lang="EN">
	<xs:include schemaLocation="include/datacite-titleType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-contributorType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-dateType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-resourceType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-relationType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-relatedIdentifierType-v2.xsd"/>
	<xs:include schemaLocation="include/datacite-descriptionType-v2.xsd"/>
	<xs:element name="resource">
		<xs:annotation>
			<xs:documentation>
	Root element of a single record. This wrapper element is for XML implementation only and is not defined in the DataCite DOI standard.
        Note: This is the case for any wrapper element within this schema!</xs:documentation>
			<xs:documentation>No content in this wrapper element.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<!--REQUIRED FIELDS-->
				<xs:element name="identifier">
					<xs:annotation>
						<xs:documentation>A persistent identifier that identifies a resource.</xs:documentation>
						<xs:documentation>Currently, only DOI is allowed.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="doiType">
								<xs:attribute name="identifierType" use="required" fixed="DOI"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="creators">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="creator" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The main researchers involved working on the data, or the authors of the publication in priority order. May be a corporate/institutional or personal name.</xs:documentation>
									<xs:documentation>Format: Family, Given.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="creatorName">
											<xs:simpleType>
												<xs:restriction base="nonemptycontentStringType"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="nameIdentifier" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="nonemptycontentStringType">
														<xs:attribute name="nameIdentifierScheme" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="titles">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>A name or title by which a resource is known.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="nonemptycontentStringType">
											<xs:attribute name="titleType" type="titleType" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="publisher">
					<xs:annotation>
						<xs:documentation>A holder of the data (including archives as appropriate) or institution which submitted the work. Any others may be listed as contributors. This property will be used to formulate the citation, so consider the prominence of the role.</xs:documentation>
						<xs:documentation>Examples: World Data Center for Climate (WDCC); GeoForschungsZentrum Potsdam (GFZ); Geological Institute, University of Tokyo </xs:documentation>
						<xs:documentation>In the case of datasets, "publish" is understood to mean making the data available to the community of researchers.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="nonemptycontentStringType"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="publicationYear">
					<xs:annotation>
						<xs:documentation>Year when the data is made publicly available. If an embargo period has been in effect, use the date when the embargo period ends.</xs:documentation>
						<xs:documentation>YYYY</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="yearType"/>
					</xs:simpleType>
				</xs:element>
				<!--OPTIONAL FIELDS-->
				<xs:element name="subjects" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="subject" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Subject, keywords, classification codes, or key phrases describing the resource.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="subjectScheme" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="contributors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="contributor" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The institution or person responsible for collecting, creating, or otherwise contributing to the development of the dataset.</xs:documentation>
									<xs:documentation>The personal name format should be: Family, Given.</xs:documentation>
								</xs:annotation>
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element name="contributorName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="nameIdentifier" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="nameIdentifierScheme" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="contributorType" type="contributorType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dates" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="date" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Different dates relevant to the work.</xs:documentation>
									<xs:documentation>YYYY or YYYY-MM-DD or any other format described in W3CDTF (http://www.w3.org/TR/NOTE-datetime) </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="dateType" type="dateType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="language" type="xs:language" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Primary language of the resource. Allowed values from: ISO 639-2/B, ISO 639-3</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="resourceType" minOccurs="0">
					<xs:annotation>
						<xs:documentation>The type of a resource. You may enter an additional free text description.</xs:documentation>
					</xs:annotation>
					<xs:complexType mixed="true">
						<xs:annotation>
							<xs:documentation>Use this attribute to choose the general type of the resource from the controlled list.</xs:documentation>
						</xs:annotation>
						<xs:attribute name="resourceTypeGeneral" type="resourceType" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="alternateIdentifiers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alternateIdentifier" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>An identifier other than the primary identifier applied to the resource being registered. This may be any alphanumeric string which is unique within its domain of issue. The format is open</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="alternateIdentifierType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="relatedIdentifiers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="relatedIdentifier" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Identifiers of related resources. Use this property to indicate subsets of properties, as appropriate.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="relatedIdentifierType" type="relatedIdentifierType" use="required"/>
											<xs:attribute name="relationType" type="relationType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sizes" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="size" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Unstructures size information about the resource. </xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="formats" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="format" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Technical format of the resource.</xs:documentation>
									<xs:documentation>Use file extension or MIME type where possible.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="version" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Version number of the resource. If the primary resource has changed the version number increases.</xs:documentation>
						<xs:documentation>Register a new DOI (or primary identifier) when the version of the resource changes to enable the citation of the exact version of a research dataset (or other resource). May be used in conjunction with properties 11 and 12 (AlternateIdentifier and RelatedIdentifier) to indicate various information updates.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="rights" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Any rights information for this resource. Provide a rights management statement for the resource or reference a service providing such information. Include embargo information if applicable.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="descriptions" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="description" maxOccurs="unbounded">
								<xs:complexType mixed="true">
									<xs:choice>
										<xs:element name="br" minOccurs="0" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="0"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:choice>
									<xs:attribute name="descriptionType" type="descriptionType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="lastMetadataUpdate" type="xs:date" use="optional"/>
			<xs:attribute name="metadataVersionNumber" type="xs:integer" use="optional"/>
			<!--ADMINISTRATIVE FIELDS-->
		</xs:complexType>
	</xs:element>
	<!-- TYPE DECLARATIONS -->
	<!-- defines the value for a DOI: DOI must start with "10."  -->
	<xs:simpleType name="doiType">
		<xs:restriction base="xs:token">
			<xs:pattern value="[1][0][/.].*"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- defines value for mandatory fields -->
	<xs:simpleType name="nonemptycontentStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="nameId">
		<xs:attribute name="nameIdentifier" type="xs:string" use="optional"/>
		<xs:attribute name="nameIdentifierScheme" type="xs:string" use="optional"/>
	</xs:attributeGroup>
	<!-- defines the value for a year -->
	<xs:simpleType name="yearType">
		<xs:restriction base="xs:token">
			<xs:pattern value="[\d]{4}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== datacite/schema/source/meta/kernel-4.3/example/datacite-example-dataset-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.3/metadata.xsd">
  <identifier identifierType="DOI">10.5072/D3P26Q35R-Test</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Fosmire, Michael</creatorName>
      <givenName>Michael</givenName>
      <familyName>Fosmire</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Wertz, Ruth</creatorName>
      <givenName>Ruth</givenName>
      <familyName>Wertz</familyName>
    </creator>
    <creator>
      <creatorName nameType="Personal">Purzer, Senay</creatorName>
       <givenName>Senay</givenName>
      <familyName>Purzer</familyName>
    </creator>
  </creators>
  <titles>
    <title xml:lang="en">Critical Engineering Literacy Test (CELT)</title>
  </titles>
  <publisher xml:lang="en">Purdue University Research Repository (PURR)</publisher>
  <publicationYear>2013</publicationYear>
  <subjects>
    <subject xml:lang="en">Assessment</subject>
    <subject xml:lang="en">Information Literacy</subject>
    <subject xml:lang="en">Engineering</subject>
    <subject xml:lang="en">Undergraduate Students</subject>
    <subject xml:lang="en">CELT</subject>
    <subject xml:lang="en">Purdue University</subject>
  </subjects>
  <language>en</language>
  <resourceType resourceTypeGeneral="Dataset">Dataset</resourceType>
  <version>1.0</version>
  <descriptions>
    <description xml:lang="en" descriptionType="Abstract">
      We developed an instrument, Critical Engineering Literacy Test (CELT), which is a multiple choice instrument designed to measure undergraduate students’ scientific and information literacy skills. It requires students to first read a technical memo
      and, based on the memo’s arguments, answer eight multiple choice and six open-ended response questions. We collected data from 143 first-year engineering students and conducted an item analysis. The KR-20 reliability of the instrument was .39. Item
      difficulties ranged between .17 to .83. The results indicate low reliability index but acceptable levels of item difficulties and item discrimination indices. Students were most challenged when answering items measuring scientific and mathematical
      literacy (i.e., identifying incorrect information).
    </description>
  </descriptions>
</resource>

=== datacite/schema/meta/kernel-2.2/example/datacite-metadata-sample-set4-dataset-v2.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-2.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-2.2 http://schema.datacite.org/meta/kernel-2.2/metadata.xsd">
	<identifier identifierType="DOI">10.5072/004</identifier>
	<creators>
		<creator>
			<creatorName>Smith, John</creatorName>
		</creator>
	</creators>
	<titles>
		<title>Drilling Core 2</title>
		<title titleType="Subtitle">A dataset</title>
	</titles>
	<publisher>TIB</publisher>
	<publicationYear>2010</publicationYear>
	<resourceType resourceTypeGeneral="Dataset"/>
	<relatedIdentifiers>
		<relatedIdentifier relatedIdentifierType="DOI" relationType="IsNewVersionOf">10.5072/001</relatedIdentifier>
		<relatedIdentifier relatedIdentifierType="DOI" relationType="IsPartOf">10.5072/005</relatedIdentifier>
	</relatedIdentifiers>
	<sizes>
		<size>6 MB</size>
	</sizes>
	<version>2</version>
</resource>

=== datacite/schema/source/meta/kernel-4/example/datacite-example-poster-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://datacite.org/schema/kernel-4"
    xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4/metadata.xsd">
    <identifier identifierType="DOI">10.82433/q80x-4z58</identifier>
    <creators>
        <creator>
            <creatorName nameType="Personal">Garcia, Sofia</creatorName>
            <givenName>Sofia</givenName>
            <familyName>Garcia</familyName>
            <nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID">
                https://orcid.org/0000-0001-5727-2427</nameIdentifier>
            <affiliation affiliationIdentifier="https://ror.org/03efmqc40"
                affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">Arizona State
                University</affiliation>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en">Persistent Identifiers in Practice: Enhancing Poster Discoverability and Reuse</title>
    </titles>
    <publisher>International Metadata Forum</publisher>
    <publicationYear>2025</publicationYear>
    <dates>
        <date dateType="Issued">2025</date>
    </dates>
    <resourceType resourceTypeGeneral="Poster">Conference poster</resourceType>
    <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="URL" relationType="Other"
        relationTypeInformation="was presented at" resourceTypeGeneral="Event">https://example.org/metadata-forum-2025</relatedIdentifier>
    </relatedIdentifiers>
    <language>en</language>
    <descriptions>
        <description xml:lang="en" descriptionType="Abstract">Posters are a key channel for sharing
            early research, yet they often disappear after the event. This poster shows how
            persistent identifiers (PIDs) can make posters easier to cite, discover, and reuse.</description>
    </descriptions>
</resource>

=== datacite/schema/source/meta/kernel-4/example/datacite-example-parallel-languages-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4/metadata.xsd">
    <identifier identifierType="DOI">10.82433/4r08-sa38</identifier>
    <creators>
        <creator>
            <creatorName nameType="Organizational">Global Seismology Research Center</creatorName>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en">Seismometer User Manual</title>
        <title xml:lang="fr">Manuel d'utilisation du sismomètre</title>
    </titles>
    <publisher>Global Seismology Research Center</publisher>
    <publicationYear>2023</publicationYear>
    <dates>
        <date dateType="Issued">2023</date>
    </dates>
    <resourceType resourceTypeGeneral="Other">Manual</resourceType>
    <language>mul</language>
    <descriptions>
        <description xml:lang="en" descriptionType="Abstract">This manual provides comprehensive instructions on the installation, calibration, and maintenance of the Global Seismology Research Center's seismometer models.</description>
        <description xml:lang="fr" descriptionType="Abstract">Ce manuel fournit des instructions complètes pour l'installation, l'étalonnage et l'entretien des modèles de sismomètres du Centre de recherche sismologique mondial.</description>
    </descriptions>
</resource>

=== datacite/schema/source/meta/kernel-4.6/example/datacite-example-coverage-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4/metadata.xsd">
    <identifier identifierType="DOI">10.82433/pgk2-ar97</identifier>
    <creators>
        <creator>
            <creatorName nameType="Organizational">European Social Fund/DABURH, Department of History, Leiden University</creatorName>
            <nameIdentifier nameIdentifierScheme="ROR" schemeURI="https://ror.org">https://ror.org/027bh9e22</nameIdentifier>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en">Amsterdam immigrants, 1578-1810</title>
        <title xml:lang="en" titleType="AlternativeTitle">Simon Hart database</title>
    </titles>
    <publisher>DANS Data Station Social Sciences and Humanities</publisher>
    <publicationYear>1995</publicationYear>
    <resourceType resourceTypeGeneral="Dataset" />
    <subjects>
        <subject>historical demography</subject>
        <subject>immigration</subject>
        <subject>Arts and Humanities</subject>
    </subjects>
    <descriptions>
        <description descriptionType="Abstract">This dataset contains information about the number and origin of the Amsterdam immigrants in the period 1578-1810. The data are subdivided in total, male and female, per region or place of origin. The dataset is based on lists compiled by the Amsterdam archivist dr. Simon Hart and his colleagues between 1960 and 1979.</description>
    </descriptions>
    <contributors>
        <contributor contributorType="ContactPerson">
            <contributorName>Data Station Admin</contributorName>
            <affiliation affiliationIdentifier="https://ror.org/008pnp284" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org/">Data Archiving and Networked Services (DANS)</affiliation>
        </contributor>
    </contributors>
    <dates>
        <date dateType="Coverage">1578-01-01/1810-12-31</date>
        <date dateType="Collected">1995-03-01/1995-11-29</date>
    </dates>
    <language>nl</language>
    <alternateIdentifiers>
        <alternateIdentifier alternateIdentifierType="NHDA">D0049</alternateIdentifier>
        <alternateIdentifier alternateIdentifierType="DANS-KNAW">easy-dataset:36690</alternateIdentifier>
    </alternateIdentifiers>
    <geoLocations>
        <geoLocation>
            <geoLocationPlace>Amsterdam</geoLocationPlace>
            <geoLocationPoint>
                <pointLatitude>52.377956</pointLatitude>
                <pointLongitude>4.897070</pointLongitude>
            </geoLocationPoint>
        </geoLocation>
    </geoLocations>
</resource>

=== datacite/schema/source/meta/kernel-4.3/example/datacite-example-relationTypeIsIdenticalTo-v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.3/metadata.xsd">
  <identifier identifierType="DOI">10.5072/10.CPoS-example</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Kreyenfeld, Michaela</creatorName>
      <givenName>Michaela</givenName>
      <familyName>Kreyenfeld</familyName>
      <nameIdentifier nameIdentifierScheme="ISNI" schemeURI="http://isni.org/isni/">0000000117540116</nameIdentifier>
    </creator>
    <creator>
      <creatorName nameType="Personal">Hornung, Anne</creatorName>
      <givenName>Anne</givenName>
      <familyName>Hornung</familyName>
      <nameIdentifier nameIdentifierScheme="VIAF" schemeURI="http://viaf.org/viaf/">304639093</nameIdentifier>
    </creator>
    <creator>
      <creatorName nameType="Personal">Kubisch, Karolin</creatorName>
      <givenName>Karolin</givenName>
      <familyName>Kubisch</familyName>
      <nameIdentifier nameIdentifierScheme="VIAF" schemeURI="http://viaf.org/viaf/">303937450</nameIdentifier>
    </creator>
  </creators>
  <titles>
    <title xml:lang="en">The German Generations and Gender Survey</title>
    <title xml:lang="en" titleType="Subtitle">Some Critical Reflections on the Validity of Fertility Histories</title>
  </titles>
  <publisher xml:lang="en">Federal Institute for Population Research, Germany</publisher>
  <publicationYear>2013</publicationYear>
  <subjects>
    <subject xml:lang="en">Fertility</subject>
    <subject xml:lang="en">Marriage</subject>
    <subject xml:lang="en">Germany</subject>
    <subject xml:lang="en">Data validation</subject>
    <subject xml:lang="en">Mikrozensus</subject>
    <subject xml:lang="en">Gender survey</subject>
    <subject xml:lang="en" schemeURI="http://www.gesis.org/en/services/research/tools-for-searching/classification" subjectScheme="GESIS">10300 Demography, Population Research</subject>
  </subjects>
  <contributors>
    <contributor contributorType="Editor">
      <contributorName xml:lang="en" nameType="Organizational">Federal Institute for Population Research</contributorName>
      <nameIdentifier nameIdentifierScheme="ISNI" schemeURI="http://isni.org/isni/">0000000094455866</nameIdentifier>
    </contributor>
  </contributors>
  <language>en</language>
  <resourceType resourceTypeGeneral="Text">Article</resourceType>
  <alternateIdentifiers>
    <alternateIdentifier alternateIdentifierType="internal ID">da|ra.14.103</alternateIdentifier>
  </alternateIdentifiers>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="URN" relationType="IsIdenticalTo">urn:nbn:de:bib-cpos-2013-02en8</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="IsIdenticalTo">10.4232/10.CPoS-2013-02en</relatedIdentifier>
  </relatedIdentifiers>
  <formats>
    <format>PDF</format>
  </formats>
  <version>1</version>
  <rightsList>
   <rights xml:lang="en-US" schemeURI="https://spdx.org/licenses/" rightsIdentifierScheme="SPDX" rightsIdentifier="CC-BY-NC-ND-3.0" rightsURI="http://creativecommons.org/licenses/by-nc-nd/3.0/deed">Creative Commons License: Attribution-NonCommercial-NoDerivs 3.0 Unported</rights>
  </rightsList>
  <descriptions>
    <description xml:lang="en" descriptionType="SeriesInformation">Comparative Population Studies Vol 38, No 1 (2013)</description>
    <description xml:lang="en" descriptionType="Abstract">This paper validates the fertility histories of the German Generations and Gender Survey (GGS). Focusing on the cohorts 1930-69 of West German women, the total number of children, the parity distribution and the parity progression ratios are comparedto external sources. One major result from this validation is that the German GGS understates the fertility for the older cohorts and overstates it for the younger ones.</description>
  </descriptions>
</resource>
